Feature/uot 92640
dod-advana/gamechanger-data pull request #35
Opened 2021-04-30 19:02 UTC by st585

Adding thumbnails into the data eng pipeline
-Generate .png from the first page of a .pdf
-upload to s3 under the "thumbnails" directory

2021-04-30 19:47 UTC, takao8 requested changes

2021-04-30 19:47 UTC, takao8 commented on common/document_parser/process.py
> +        filetype.guess(str(x)).mime == "pdf" or filetype.guess(str(x)) != "application/pdf")]
this line needs to be changed back, the removed line is the correct check

```suggestion
        filetype.guess(str(x)).mime == "pdf" or filetype.guess(str(x)).mime == "application/pdf")]
```

2021-04-30 20:01 UTC, takao8 approved these changes

2021-05-03 02:30 UTC, vctrstrm requested changes
@meglynkau @st585 @takao8   Core logic seems solid, but let's meet to see if it may be better to pull the thumbnail generation into a separate utility/functionality or something specific to policy analytics pipeline of the docparser. Also maybe good to pull in @dakotahavel

2021-06-14 16:37 UTC, closed without merging