rename dev to dev_tools and update where needed
dod-advana/gamechanger-data pull request #48
Opened 2021-05-10 19:02 UTC by dakotahavel

2021-05-11 14:18 UTC, vctrstrm submitted a review, later dismissed

2021-06-22 04:52 UTC, meglynkau submitted a review, later dismissed

2021-06-22 08:30 UTC, vctrstrm requested changes
seems some other changes snuck into this PR (judging by the diff). Please rebase on dev to include only the relevant changes.

2021-07-01 21:50 UTC, takao8 commented
this was a messy rebase, going to check carefully that everything was transferred correctly

2021-07-01 22:55 UTC, vctrstrm approved these changes

2021-07-01 22:57 UTC, takao8 approved these changes

2021-07-01 23:00 UTC, meglynkau approved these changes

2021-07-01 23:32 UTC, merged