Task/uot 96946
dod-advana/gamechanger-data pull request #57
Opened 2021-05-17 17:53 UTC by rha930

- updating ingest to allow combined entities ingest

2021-05-17 18:01 UTC, rha930 commented
most of the changes are just from autopep

2021-05-19 13:54 UTC, rha930 commented
python -m dataPipelines.gc_elasticsearch_publisher entity-insert -i entities --entity-csv-path './dataScience/data/combined_entities.csv' -m configuration/elasticsearch-config/dev-entities.json

2021-05-19 19:52 UTC, vctrstrm requested changes

2021-05-19 19:52 UTC, vctrstrm commented on .gitmodules
> +  ignore = dirty
need to match indent

2021-05-19 19:57 UTC, vctrstrm approved these changes

2021-05-19 19:57 UTC, merged